# Create a new Role of nginx ingress controller

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  name: ingress-nginx
  namespace: ingress-nginx
rules:
# Allow to get namespace
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get

# Allow to get, list, watch configmaps, pods, secrets, endpoints
- apiGroups:
  - ""
  resources:
  - configmaps
  - pods
  - secrets
  - endpoints
  verbs:
  - get
  - list
  - watch

# Allow to get, list, watch services
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch

# Allow to get, list, watch ingresses
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch

# Allow to update ingresses/status
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/status
  verbs:
  - update

# Allow to get, list, watch ingressclasses
- apiGroups:
  - networking.k8s.io
  resources:
  - ingressclasses
  verbs:
  - get
  - list
  - watch

# Allow to get, update leases
- apiGroups:
  - coordination.k8s.io
  resourceNames:
  - ingress-nginx-leader
  resources:
  - leases
  verbs:
  - get
  - update

# Allow to create leases
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create

# Allow to create, patch events
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch

# Allow to list, watch, get endpointslices
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - list
  - watch
  - get
---
# Create RoleBinding for the above Role (ingress-nginx) with ServiceAccount (ingress-nginx)
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  name: ingress-nginx
  namespace: ingress-nginx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ingress-nginx
subjects:
- kind: ServiceAccount
  name: ingress-nginx
  namespace: ingress-nginx