resources:
  - ../../base
  - db-sealedcreds.yaml
  - db-configmap.yaml

namePrefix: dev-

patchesStrategicMerge:
  - replicas-patch-app.yaml

#secretGenerator:
#  - name: db-creds
#    literals:
#      - DB_USER=admin
#      - DB_PASSWORD=<EMPTY>

#configMapGenerator:
#  - name: db-config
#    literals:
#      - DB_HOST=db-service
#      - DB_PORT=5432
#      - DB_NAME=quanrestaurantdb
#      - DB_SSLMODE=disable

#configurations:
#  - configurations/sealed-secret-config.yaml

#generatorOptions:
#  annotations:
#    sealedsecrets.bitnami.com/managed: "true"
