apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    deployment: app
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: app
  template:
    metadata:
      labels:
        pod: app
    spec:
      initContainers:
        - name: init-db
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              until nc -z -v -w30 db-service 5432; do
                echo "Waiting for PostgreSQL to be ready...";
                sleep 5;
              done
      containers:
      - name: app
        image: <IMAGE-HERE>
        ports:
          - containerPort: 8080
            name: http-app
        resources:
          requests:
            memory: "<CHANGE ME>"
            cpu: "<CHANGE ME>"
          limits:
            memory: "<CHANGE ME>"
            cpu: "<CHANGE ME>"
        securityContext:
          runAsUser: 0 # <CHANGE ME> - Currently running as root, shouldn't do this
          runAsGroup: 0 # <CHANGE ME> - Currently running as root group, shouldn't do this
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        envFrom:
          - configMapRef:
              name: db-config
          - secretRef:
              name: db-creds
