apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    deployment: db
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: db
  template:
    metadata:
      labels:
        pod: db
    spec:
      securityContext:
        fsGroup: 70 # ADDED JUST FOR TESTING
      volumes:
        - name: db-pv-storage
          persistentVolumeClaim:
            claimName: db-pvc
      containers:
        - name: db
          image: postgres:17.5-alpine3.22
          ports:
            - containerPort: 5432
              name: postgres-port
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-pv-storage
          resources:
            requests:
              memory: "256Mi" # JUST FOR TESTING
              cpu: "125m" # JUST FOR TESTING
            limits:
              memory: "512Mi" # JUST FOR TESTING
              cpu: "250m" # JUST FOR TESTING
          securityContext:
            runAsUser: 70 # FOR TESTING
            runAsGroup: 70 # FOR TESTING
            runAsNonRoot: true # FOR TESTING
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - admin
                - -d
                - quanrestaurantdb
                - -p
                - "5432"
            initialDelaySeconds: 5
            periodSeconds: 3
          env: # JUST FOR TESTING (Move this to SealedSecret)
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_DB
              value: quanrestaurantdb