apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
    name: db-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  local:
    path: /mnt/data/postgresql # Local disk path on the node
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - hungnx-secondarchpc
