apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
    name: db-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  local:
    path: /mnt/data/postgresql
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/control-plane # JUST FOR TESTING
            operator: In
            values:
              - "true" # JUST FOR TESTING