apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    service: db
spec:
  type: ClusterIP
  selector:
    pod: db
  ports:
    - name: tcp
      protocol: TCP
      port: 5432
      targetPort: postgres-port