apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgen-deployment
  labels:
    app: loadgen
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loadgen
  template:
    metadata:
      labels:
        app: loadgen
    spec:
      containers:
        - name: hey
          image: ricoli/hey
          args:
            - "-z"
            - "10m"
            - "-q"
            - "100"
            - "http://nginx-service.default.svc.cluster.local"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
