apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    deployment: db
spec:
  replicas: 2
  selector:
    matchLabels:
      pod: db
  template:
    metadata:
      labels:
        pod: db
    spec:
      volumes:
        - name: db-pv-storage
          persistentVolumeClaim:
            claimName: db-pvc
      containers:
        - name: db
          image: postgres:17.5-alpine3.22
          ports:
            - containerPort: 5432
              name: postgres-port
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-pv-storage
          resources:
            requests:
              memory: "<CHANGE ME>"
              cpu: "<CHANGE ME>"
            limits:
              memory: "<CHANGE ME>"
              cpu: "<CHANGE ME>"
          securityContext:
            runAsUser: 0 # <CHANGE ME> - Currently running as root, shouldn't do this
            runAsGroup: 0 # <CHANGE ME> - Currently running as root group, shouldn't do this
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - admin
                - -d
                - quanrestaurantdb
                - -h
                - db-service
                - -p
                - "5432"
            initialDelaySeconds: 5
            periodSeconds: 3