apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    service: app
spec:
  type: ClusterIP
  selector:
    pod: app
  ports:
  - name: http 
    protocol: TCP
    port: 8080
    targetPort: http-app
